# ── Profil Docker — surcharge application.properties ──────────────────────────
# Ces valeurs sont injectées via les variables d'environnement du docker-compose

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/pronunciation_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789}

python.base-url=${PYTHON_BASE_URL:http://fastapi:8000}

ollama.base-url=${OLLAMA_BASE_URL:http://host.docker.internal:11434}
ollama.model=${OLLAMA_MODEL:qwen2.5:3b}
ollama.model.chatbot=${OLLAMA_MODEL_CHATBOT:qwen2.5:3b}

# JWT : on utilise jwk-set-uri pour l'URL interne, mais il faut garder le VRAI issuer pour valider le token
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8090/realms/talan}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://host.docker.internal:8090/realms/talan/protocol/openid-connect/certs}

keycloak.admin.url=${KEYCLOAK_ADMIN_URL:http://host.docker.internal:8090}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:talan}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:talan-frontend}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:Admin1234!}

app.frontend.url=${APP_FRONTEND_URL:http://localhost:8081}
app.storage.audio-dir=${APP_STORAGE_AUDIO_DIR:./storage/audio}
app.storage.video-dir=${APP_STORAGE_VIDEO_DIR:./storage/videos}
app.storage.image-dir=${APP_STORAGE_IMAGE_DIR:./storage/images}
